set_property PACKAGE_PIN B11 [get_ports hs]
set_property IOSTANDARD LVCMOS33 [get_ports hs]
set_property PACKAGE_PIN B12 [get_ports vs]
set_property IOSTANDARD LVCMOS33 [get_ports vs]
set_property PACKAGE_PIN P17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
